// ============================================================
// routefolk — screens/render/desktop.js
// Full desktop renderer for the production redesign.
// No mobile rendering, no post-render patching.
// ============================================================

import { STATE } from '../../state/app-state.js';
import { esc } from '../../utils/dom.js';
import { fmtDate, fmtDateRange } from '../../utils/datetime.js';
import { STATUS_META } from '../../constants/app-constants.js';
import {
  ARCHIVE_FILTERS,
  DETAIL_TABS,
  aggregateExpense,
  archiveTrips,
  arr,
  categoryLabel,
  currentTrip,
  day,
  expenses,
  fmtEuro,
  initials,
  lifetime,
  payerName,
  season,
  stages,
  stats,
  subtitle,
  tripNo,
  userName,
} from './shared.js';
import { gpxPanelHtml } from './trip-detail/gpx-panel.js';
import { renderAccount, renderSignedOutMarkup } from './account/account-desktop.js';
import { renderCosts as renderCostsImpl } from './trip-detail/costs-desktop.js';
import { renderItems as renderItemsImpl } from './trip-detail/packing-desktop.js';
import { renderArchive as renderArchiveImpl } from './archive/archive-list-desktop.js';

export { renderSignedOutMarkup };

const TRIP_FILTERS = [['all', 'All'], ['planning', 'Planning'], ['active', 'Active']];
const rawStages = (tripId) => STATE.stagesByTrip[tripId];

function tripView() { if (STATE.view === 'summary') return 'summary'; if (STATE.view === 'costs') return 'costs'; if (STATE.view === 'packing') return 'items'; if (STATE.view === 'journal') return 'journal'; return 'stages'; }
function statusName(status) { return STATUS_META[status]?.label || String(status || 'Planning'); }
function loadingHtml(label = 'Loading…') { return `<div class="rf-d2-empty is-loading">${esc(label)}</div>`; }
function errorHtml(error) { return error ? `<div class="rf-d2-empty is-error">${esc(error)}</div>` : ''; }
function statePill(status) { return `<span class="rf-d2-state-pill is-${esc(status || 'planning')}"><span class="rf-d2-state-dot"></span>${esc(statusName(status))}</span>`; }
function stamp(text, kind = 'primary') { return `<span class="rf-d2-stamp is-${esc(kind)}">${esc(text)}</span>`; }
function activeTrips() { const q = (STATE.tripSearch || '').trim().toLowerCase(); const f = STATE.tripStatusFilter || 'all'; return STATE.trips.filter(t => ['planning','active'].includes(t.status)).filter(t => (f === 'all' || t.status === f) && (!q || `${t.title || ''} ${t.description || ''}`.toLowerCase().includes(q))); }
function filters(options, active, action = 'status-filter') { return `<div class="rf-d2-pills">${options.map(([key, label]) => `<button class="rf-d2-pill ${active === key ? 'is-active' : ''}" data-action="rf-d2-${action}" data-value="${esc(key)}" type="button">${esc(label)}</button>`).join('')}</div>`; }
function search(open, value) { return open ? `<div class="rf-d2-search"><input type="search" data-action="rf-d2-search-input" value="${esc(value || '')}" placeholder="Search by name"><button class="rf-d2-search-close" data-action="rf-d2-search-toggle" type="button">×</button></div>` : `<button class="rf-d2-search-btn" data-action="rf-d2-search-toggle" type="button" aria-label="Search">⌕</button>`; }
function tabs(active) { return `<nav class="rf-d2-selector-tabs">${DETAIL_TABS.map(([key, label]) => `<button class="rf-d2-selector-tab ${active === key ? 'is-active' : ''}" data-action="rf-d2-tab" data-value="${key}" type="button">${esc(label)}</button>`).join('')}</nav>`; }
function hero(trip, opts = {}) { const { withStats = false, backAction = 'rf-d2-back-to-trips' } = opts; const s = stats(trip); const visibility = trip.visibility === 'private' ? 'Private' : 'Group'; return `<header class="rf-d2-hero"><div class="rf-d2-hero-top"><div><button class="rf-d2-back" data-action="${backAction}" type="button">← ${backAction.includes('archive') ? 'Archive' : 'Trips'}</button><div class="rf-d2-kicker">${esc(tripNo(trip))} · ${esc(season(trip))}</div><h1 class="rf-d2-hero-title">${esc(trip.title || 'Untitled trip')}</h1><div class="rf-d2-hero-sub">${esc(subtitle(trip))}</div></div><div class="rf-d2-hero-stamps">${statePill(trip.status)}${stamp(visibility,'accent')}</div></div>${withStats ? `<div class="rf-d2-stat-grid"><div><span>Distance</span><strong>${Math.round(s.distance).toLocaleString()}</strong><small>km recorded</small></div><div><span>Spent</span><strong>${fmtEuro(s.spent)}</strong><small>so far</small></div><div><span>Stages</span><strong>${s.stages}</strong><small>days</small></div><div><span>Entries</span><strong>${s.entries}</strong><small>journal</small></div></div>` : ''}</header>`; }
function numeric(value) { const number = Number(value); return Number.isFinite(number) ? number : null; }
function stageHasCoords(stage) { return (numeric(stage?.start_lat) !== null && numeric(stage?.start_lng) !== null) || (numeric(stage?.end_lat) !== null && numeric(stage?.end_lng) !== null); }
function forecastTempRange(forecast) { if (forecast?.tempMin != null && forecast?.tempMax != null) return `${Math.round(forecast.tempMin)}–${Math.round(forecast.tempMax)}°`; return '—'; }
function forecastMeta(forecast) { const precip = forecast?.precipProb != null ? `${Math.round(forecast.precipProb)}% rain` : forecast?.precipMm != null ? `${forecast.precipMm} mm rain` : 'rain —'; const wind = forecast?.windKmh != null ? `${Math.round(forecast.windKmh)} km/h wind` : 'wind —'; return `${precip} · ${wind}`; }
function desktopSkyPoint(point) { const forecast = point?.forecast || null; return `<div><strong>${esc(point?.label || 'Point')}</strong><br>${esc(forecast?.icon || '·')}<br><span>${esc(forecastTempRange(forecast))}</span><small>${esc(forecastMeta(forecast))}</small></div>`; }
function desktopSkyMessage(message) { return `<div class="rf-d2-sky"><div class="rf-d2-sky-tag">Sky advisory</div><div class="rf-d2-mini-table">${esc(message)}</div></div>`; }
function desktopSkyHtml(stage) { const result = STATE.forecastsByStage[stage.id]; if (!stage?.planned_date) return desktopSkyMessage('Set a planned date to see the weather forecast.'); if (!stageHasCoords(stage)) return desktopSkyMessage('Weather unavailable. Edit the stage location so routefolk can store coordinates.'); if (result === 'loading' || result === undefined) return desktopSkyMessage('Loading weather…'); if (!Array.isArray(result) || !result.length) return desktopSkyMessage('Weather unavailable for this stage.'); const usable = result.filter(point => point.forecast); if (!usable.length) return desktopSkyMessage('No forecast available for this date.'); return `<div class="rf-d2-sky"><div class="rf-d2-sky-tag">Sky advisory</div><div class="rf-d2-sky-grid">${result.map(desktopSkyPoint).join('')}</div><div class="rf-v2-archive-map-status">Weather by Open-Meteo</div></div>`; }

export function renderDesktopMarkup() { if (STATE.tripsLoading && !STATE.trips.length) return `<div class="rf-d2-app"><main class="rf-d2-main">${loadingHtml('Loading trips…')}</main></div>`; if (STATE.tripsError) return `<div class="rf-d2-app"><main class="rf-d2-main">${errorHtml(STATE.tripsError)}</main></div>`; const trip = currentTrip(); const thirdPane = STATE.tab === 'trips' && trip && !['summary','costs','items'].includes(tripView()); let body = ''; if (STATE.tab === 'archive') body = renderArchive(); else if (STATE.tab === 'account') body = renderAccount(); else if (!trip) body = renderTripList(null) + renderLanding(); else body = renderTripList(trip.id) + renderTripView(trip); return `<div class="rf-d2-app ${thirdPane ? 'is-3-pane' : ''}">${renderSidebar(thirdPane)}${body}</div>`; }
function renderSidebar(collapsed) { const l = lifetime(); return `<aside class="rf-d2-sidebar ${collapsed ? 'is-collapsed' : ''}"><div class="rf-d2-sidebar-head">${collapsed ? '<div class="rf-d2-sidebar-mark">r</div><div class="rf-d2-sidebar-mark-sub">routefolk</div>' : '<div class="rf-d2-sidebar-kicker">Routefolk</div><div class="rf-d2-sidebar-title">Field journal</div>'}</div><nav class="rf-d2-rail">${[['trips','T','Trips'],['archive','A','Archive'],['account','Y','You']].map(([key,glyph,label])=>`<button class="rf-d2-rail-item ${STATE.tab===key?'is-active':''}" data-action="rf-d2-nav" data-tab="${key}" type="button"><span class="rf-d2-rail-glyph">${glyph}</span><span class="rf-d2-rail-label">${label}</span></button>`).join('')}</nav><div class="rf-d2-sidebar-spacer"></div><div class="rf-d2-lifetime"><div class="rf-d2-lifetime-kicker">Lifetime</div><div class="rf-d2-lifetime-row"><span>${l.trips}</span><span>${Math.round(l.distance).toLocaleString()}</span></div><div class="rf-d2-lifetime-labels"><span>Trips</span><span>km</span></div></div><div class="rf-d2-user"><span class="rf-d2-user-avatar">${esc(initials())}</span><span class="rf-d2-user-meta"><strong>${esc(userName())}</strong></span></div></aside>`; }
function renderTripList(selected) { return `<aside class="rf-d2-trips-col"><div class="rf-d2-trips-head"><div><div class="rf-d2-kicker">The road map</div><h1 class="rf-d2-col-title">Trips</h1><div class="rf-d2-col-sub">${activeTrips().length} on the road map · ${archiveTrips().length} in archive</div></div><button class="rf-d2-btn is-primary" data-action="rf-d2-new-trip" type="button">+ New</button></div><div class="rf-d2-filter-row">${filters(TRIP_FILTERS, STATE.tripStatusFilter || 'all')}${search(STATE.tripFiltersOpen || !!STATE.tripSearch, STATE.tripSearch)}</div><div class="rf-d2-master-list">${activeTrips().map(t => renderTripRow(t, selected)).join('') || '<div class="rf-d2-empty">No matching trips.</div>'}</div></aside>`; }
function renderTripRow(trip, selected) { const s = stats(trip); return `<button class="rf-d2-trip-row ${selected === trip.id ? 'is-selected' : ''}" data-action="rf-d2-select-trip" data-trip-id="${esc(trip.id)}" type="button"><div class="rf-d2-trip-row-no">${esc(tripNo(trip))}</div><div class="rf-d2-trip-row-title">${esc(trip.title || 'Untitled trip')}</div><div class="rf-d2-trip-row-sub">${esc(subtitle(trip))}</div><div class="rf-d2-trip-row-meta"><span>${esc(fmtDateRange(trip.start_date, trip.end_date))}</span><span>${Math.round(s.distance).toLocaleString()} km</span><span>${s.stages} st</span></div>${statePill(trip.status)}</button>`; }
function renderLanding() { const trip = activeTrips()[0]; return `<main class="rf-d2-main">${trip ? hero(trip,{withStats:true}) : '<div class="rf-d2-empty-card">No trips yet.</div>'}<div class="rf-d2-hint">Click a trip on the left to open it. The trip expands into stages and a detail pane.</div></main>`; }
function renderTripView(trip) { const view = tripView(); if (view === 'summary') return renderSummary(trip); if (view === 'costs') return renderCosts(trip); if (view === 'items') return renderItems(trip); return renderStages(trip); }
function renderStages(trip) { const raw = rawStages(trip.id); if (raw === 'loading' || STATE.stagesLoading) return `<main class="rf-d2-main">${hero(trip,{withStats:true})}${tabs('stages')}${loadingHtml('Loading stages…')}</main><aside class="rf-d2-aside">${loadingHtml('Loading detail…')}</aside>`; const st = stages(trip.id); const selected = st.find(stage => stage.id === STATE.selectedStageId) || st[0]; return `<main class="rf-d2-main">${hero(trip,{withStats:true})}${tabs('stages')}<div class="rf-d2-section-head"><div class="rf-d2-section-title">${st.length} stages</div><button class="rf-d2-btn is-primary" data-action="rf-d2-add-stage" type="button">+ Add stage</button></div><div class="rf-d2-stage-list">${st.map((stage,i)=>renderStageRow(stage,i,selected?.id)).join('')}<button class="rf-d2-btn is-dashed" data-action="rf-d2-add-stage" type="button">+ Add another stage</button></div></main>${renderAside(trip,selected)}`; }
function renderStageRow(stage, index, selectedId) { return `<button class="rf-d2-stage-row ${selectedId === stage.id ? 'is-selected' : ''}" data-action="rf-d2-select-stage" data-stage-id="${esc(stage.id)}" type="button"><div class="rf-d2-stage-no-col"><div class="rf-d2-stage-no">${index + 1}</div><div class="rf-d2-stage-rule"></div><div class="rf-d2-stage-day">${esc(day(stage.planned_date))}</div></div><div class="rf-d2-stage-body"><div class="rf-d2-stage-row-head"><div class="rf-d2-stage-title">${esc(stage.start_location || 'Start')} <span class="rf-d2-stage-to">to</span> ${esc(stage.end_location || 'End')}</div></div><div class="rf-d2-stage-high">${esc(stage.notes || '')}</div><div class="rf-d2-stage-mono"><span><span class="rf-d2-stage-mono-label">dist</span> ${Math.round(Number(stage.distance_km) || 0)}km</span><span>${esc(fmtDate(stage.planned_date) || '')}</span></div></div></button>`; }
function stageTracks(tripId, stageId) { const raw = STATE.gpxByTrip[tripId]; return Array.isArray(raw) ? raw.filter((track) => track.stage_id === stageId) : []; }
function renderAside(trip, stage) { if (STATE.wizard === 'stage') return renderStageWizard(trip); if (STATE.wizard === 'journal') return renderJournalWizard(); if (!stage) return '<aside class="rf-d2-aside"><div class="rf-d2-empty">Select a stage.</div></aside>'; const rawEntries = STATE.entriesByStage[stage.id]; const entries = arr(rawEntries); const stageExpenses = expenses(trip.id).filter(e => e.stage_id === stage.id); const tracks = stageTracks(trip.id, stage.id); return `<aside class="rf-d2-aside"><div class="rf-d2-aside-head"><div class="rf-d2-aside-kicker">Stage ${esc(stage.order_index || '')} · ${esc(fmtDate(stage.planned_date) || '')}</div><h2 class="rf-d2-aside-title">${esc(stage.start_location || 'Start')} <span style="font-style:italic;color:var(--rf-d2-muted)">to</span> ${esc(stage.end_location || 'End')}</h2><div class="rf-d2-aside-sub">${esc(stage.notes || '')}</div></div>${desktopSkyHtml(stage)}<div class="rf-d2-section-head"><div class="rf-d2-section-title">The day's notes</div><button class="rf-d2-btn is-primary" data-action="rf-d2-add-journal" type="button">+ Add</button></div>${rawEntries === 'loading' ? loadingHtml('Loading notes…') : entries.map(entryHtml).join('') || '<div class="rf-d2-mini-table">No entries yet.</div>'}<div class="rf-d2-section-head"><div class="rf-d2-section-title">Stage costs</div><button class="rf-d2-btn is-primary" data-action="rf-v2-add-stage-expense" data-stage-id="${esc(stage.id)}" type="button">+ Add</button></div><div class="rf-d2-mini-table">${stageExpenses.map(expenseMini).join('') || 'No costs assigned to this stage.'}</div><section class="rf-v2-gpx-section">${gpxPanelHtml(trip, stage, tracks)}</section></aside>`; }
function entryHtml(entry, index) { const time = entry.timestamp ? new Date(entry.timestamp).toLocaleTimeString([], { hour:'2-digit', minute:'2-digit' }) : ''; return `<div class="rf-d2-entry"><div class="rf-d2-entry-bullet">${index + 1}</div><div><div class="rf-d2-entry-head"><div class="rf-d2-entry-type">A ${esc(entry.entry_type || 'note')}</div><div class="rf-d2-entry-when">${esc(time)}</div></div><div class="rf-d2-entry-title">${esc(entry.title || 'Untitled')}</div><div class="rf-d2-entry-loc">${entry.location ? `at ${esc(entry.location)}` : ''}</div></div></div>`; }
function expenseMini(expense) { return `<div class="rf-d2-mini-table-row"><div><div class="rf-d2-mini-cat">${esc(categoryLabel(expense.category))}</div><div class="rf-d2-mini-meta">${esc(payerName(expense.user_id))}</div></div><div>${esc(fmtEuro(expense.amount || 0))}</div></div>`; }
function renderStageWizard(trip) { return `<aside class="rf-d2-aside"><div class="rf-d2-aside-head"><div class="rf-d2-aside-kicker">New stage</div><h2 class="rf-d2-aside-title">Add a stage</h2></div><input class="rf-d2-input" id="v2-stage-from" placeholder="From"><input class="rf-d2-input" id="v2-stage-to" placeholder="To"><input class="rf-d2-input" id="v2-stage-date" type="date" value="${esc(trip.start_date || '')}"><input class="rf-d2-input" id="v2-stage-km" inputmode="decimal" placeholder="Distance km"><textarea class="rf-d2-textarea" id="v2-stage-notes" placeholder="Notes"></textarea><div class="rf-d2-form-actions"><button class="rf-d2-btn" data-action="rf-d2-cancel-wizard">Cancel</button><button class="rf-d2-btn is-primary" data-action="rf-d2-save-stage">Save stage</button></div></aside>`; }
function renderJournalWizard() { return `<aside class="rf-d2-aside"><div class="rf-d2-aside-head"><div class="rf-d2-aside-kicker">New entry</div><h2 class="rf-d2-aside-title">A note from the road</h2></div><input class="rf-d2-input" id="v2-entry-title" placeholder="Title"><input class="rf-d2-input" id="v2-entry-place" placeholder="Place"><input class="rf-d2-input" id="v2-entry-time" type="time"><textarea class="rf-d2-textarea" id="v2-entry-note" placeholder="What happened here?"></textarea><div class="rf-d2-form-actions"><button class="rf-d2-btn" data-action="rf-d2-cancel-wizard">Cancel</button><button class="rf-d2-btn is-primary" data-action="rf-d2-save-journal">Save entry</button></div></aside>`; }
function renderSummary(trip) { const s = stats(trip); return `<main class="rf-d2-main is-wide">${hero(trip)}${tabs('summary')}<div class="rf-d2-section-title">By stage</div>${summaryTable(trip)}<div class="rf-d2-total-strip"><div><span>Total distance</span><strong>${Math.round(s.distance).toLocaleString()} km</strong></div><div><span>Total spent</span><strong>${fmtEuro(s.spent)}</strong></div><div><span>Journal</span><strong>${s.entries} entries</strong></div></div></main>`; }
function summaryTable(trip) { const rows = stages(trip.id).map((stage,i)=>{ const entries = arr(STATE.entriesByStage[stage.id]); return `<div class="rf-clean-table-row"><span>${i+1}</span><strong>${esc(stage.start_location || 'Start')} to ${esc(stage.end_location || 'End')}</strong><span>${esc(fmtDate(stage.planned_date) || '—')}</span><span>${Math.round(Number(stage.distance_km) || 0)} km</span><span>${esc(stage.notes || '—')}</span></div>${entries.map((entry,j)=>`<div class="rf-clean-summary-entry"><span></span><strong>${j+1}. ${esc(entry.title || 'Untitled entry')}</strong><span>${entry.timestamp ? esc(new Date(entry.timestamp).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})) : '—'}</span><span>${esc(entry.entry_type || 'note')}</span><span>${esc(entry.location || entry.description || 'Journal entry')}</span></div>`).join('')}`; }).join(''); return `<div class="rf-clean-table"><div class="rf-clean-table-head"><span>Stage</span><span>Route / journal</span><span>Date / time</span><span>Distance / type</span><span>Notes / place</span></div>${rows || '<div class="rf-d2-empty">No stages yet.</div>'}</div>`; }
function renderCosts(trip) { return renderCostsImpl(trip, { hero, tabs, stamp }); }
function renderItems(trip) { return renderItemsImpl(trip, { hero, tabs, stamp, filters, loadingHtml }); }
function renderArchive() { return renderArchiveImpl({ hero, summaryTable, filters, search, stamp, loadingHtml }); }
