// ============================================================
// routefolk — screens/render/desktop.js
// Full desktop renderer for the production redesign.
// No mobile rendering, no post-render patching.
// ============================================================

import { STATE } from '../../state/app-state.js';
import { esc } from '../../utils/dom.js';
import { fmtDate, fmtDateRange } from '../../utils/datetime.js';
import { STATUS_META } from '../../constants/app-constants.js';
import {
  ARCHIVE_FILTERS,
  DETAIL_TABS,
  aggregateExpense,
  archiveTrips,
  arr,
  avatarUrl,
  categories,
  categoryLabel,
  currentTrip,
  day,
  expenses,
  fmtEuro,
  initials,
  items,
  lifetime,
  memberSinceYear,
  palettePanel,
  payerName,
  season,
  slug,
  stages,
  stats,
  subtitle,
  tripNo,
  userName,
} from './shared.js';

const TRIP_FILTERS = [['all', 'All'], ['planning', 'Planning'], ['active', 'Active']];
const ITEM_FILTERS = [['all', 'All'], ['planned', 'Planned'], ['packed', 'Packed'], ['optional', 'Optional']];
const rawStages = (tripId) => STATE.stagesByTrip[tripId];
const rawItems = (tripId) => STATE.itemsByTrip[tripId];

function tripView() { if (STATE.view === 'summary') return 'summary'; if (STATE.view === 'costs') return 'costs'; if (STATE.view === 'packing') return 'items'; if (STATE.view === 'journal') return 'journal'; return 'stages'; }
function statusName(status) { return STATUS_META[status]?.label || String(status || 'Planning'); }
function profileAvatar() { const url = avatarUrl(); return url ? `<img src="${esc(url)}" alt="${esc(userName())}">` : esc(initials()); }
function loadingHtml(label = 'Loading…') { return `<div class="rf-d2-empty is-loading">${esc(label)}</div>`; }
function errorHtml(error) { return error ? `<div class="rf-d2-empty is-error">${esc(error)}</div>` : ''; }
function statePill(status) { return `<span class="rf-d2-state-pill is-${esc(status || 'planning')}"><span class="rf-d2-state-dot"></span>${esc(statusName(status))}</span>`; }
function stamp(text, kind = 'primary') { return `<span class="rf-d2-stamp is-${esc(kind)}">${esc(text)}</span>`; }
function activeTrips() { const q = (STATE.tripSearch || '').trim().toLowerCase(); const f = STATE.tripStatusFilter || 'all'; return STATE.trips.filter(t => ['planning','active'].includes(t.status)).filter(t => (f === 'all' || t.status === f) && (!q || `${t.title || ''} ${t.description || ''}`.toLowerCase().includes(q))); }
function filters(options, active, action = 'status-filter') { return `<div class="rf-d2-pills">${options.map(([key, label]) => `<button class="rf-d2-pill ${active === key ? 'is-active' : ''}" data-action="rf-d2-${action}" data-value="${esc(key)}" type="button">${esc(label)}</button>`).join('')}</div>`; }
function search(open, value) { return open ? `<div class="rf-d2-search"><input type="search" data-action="rf-d2-search-input" value="${esc(value || '')}" placeholder="Search by name"><button class="rf-d2-search-close" data-action="rf-d2-search-toggle" type="button">×</button></div>` : `<button class="rf-d2-search-btn" data-action="rf-d2-search-toggle" type="button" aria-label="Search">⌕</button>`; }
function tabs(active) { return `<nav class="rf-d2-selector-tabs">${DETAIL_TABS.map(([key, label]) => `<button class="rf-d2-selector-tab ${active === key ? 'is-active' : ''}" data-action="rf-d2-tab" data-value="${key}" type="button">${esc(label)}</button>`).join('')}</nav>`; }
function route(trip) { const st = stages(trip.id); const from = st[0]?.start_location || 'Start'; const to = st[st.length - 1]?.end_location || 'End'; return `<div class="rf-d2-route"><div class="rf-d2-route-labels"><span>${esc(from)}</span><span>${esc(to)}</span></div><svg viewBox="0 0 780 120"><path d="M48 80 C150 36 250 92 355 58 S535 46 724 74"></path>${[48,188,328,468,608,724].map((x,i)=>`<circle cx="${x}" cy="${i===0?80:i===5?74:66}" r="5"/>`).join('')}</svg></div>`; }
function hero(trip, opts = {}) { const { withStats = false, withRoute = false, backAction = 'rf-d2-back-to-trips' } = opts; const s = stats(trip); const visibility = trip.visibility === 'private' ? 'Private' : 'Group'; return `<header class="rf-d2-hero"><div class="rf-d2-hero-top"><div><button class="rf-d2-back" data-action="${backAction}" type="button">← ${backAction.includes('archive') ? 'Archive' : 'Trips'}</button><div class="rf-d2-kicker">${esc(tripNo(trip))} · ${esc(season(trip))}</div><h1 class="rf-d2-hero-title">${esc(trip.title || 'Untitled trip')}</h1><div class="rf-d2-hero-sub">${esc(subtitle(trip))}</div></div><div class="rf-d2-hero-stamps">${statePill(trip.status)}${stamp(visibility,'accent')}</div></div>${withStats ? `<div class="rf-d2-stat-grid"><div><span>Distance</span><strong>${Math.round(s.distance).toLocaleString()}</strong><small>km recorded</small></div><div><span>Spent</span><strong>${fmtEuro(s.spent)}</strong><small>so far</small></div><div><span>Stages</span><strong>${s.stages}</strong><small>days</small></div><div><span>Entries</span><strong>${s.entries}</strong><small>journal</small></div></div>` : ''}${withRoute ? route(trip) : ''}</header>`; }

export function renderSignedOutMarkup() { return `<div class="rf-auth-shell"><section class="rf-auth-card"><div class="rf-d2-kicker">Routefolk</div><h1>Field journal for the road</h1><p>Plan routes, record stages, keep notes, costs, packing lists and GPX tracks in one road journal.</p><button class="rf-d2-btn is-primary" data-action="rf-d2-sign-in" type="button">Sign in with Google</button></section></div>`; }
export function renderDesktopMarkup() { if (STATE.tripsLoading && !STATE.trips.length) return `<div class="rf-d2-app"><main class="rf-d2-main">${loadingHtml('Loading trips…')}</main></div>`; if (STATE.tripsError) return `<div class="rf-d2-app"><main class="rf-d2-main">${errorHtml(STATE.tripsError)}</main></div>`; const trip = currentTrip(); const thirdPane = STATE.tab === 'trips' && trip && !['summary','costs','items'].includes(tripView()); let body = ''; if (STATE.tab === 'archive') body = renderArchive(); else if (STATE.tab === 'account') body = renderAccount(); else if (!trip) body = renderTripList(null) + renderLanding(); else body = renderTripList(trip.id) + renderTripView(trip); return `<div class="rf-d2-app ${thirdPane ? 'is-3-pane' : ''}">${renderSidebar(thirdPane)}${body}</div>`; }
function renderSidebar(collapsed) { const l = lifetime(); return `<aside class="rf-d2-sidebar ${collapsed ? 'is-collapsed' : ''}"><div class="rf-d2-sidebar-head">${collapsed ? '<div class="rf-d2-sidebar-mark">r</div><div class="rf-d2-sidebar-mark-sub">routefolk</div>' : '<div class="rf-d2-sidebar-kicker">Routefolk</div><div class="rf-d2-sidebar-title">Field journal</div>'}</div><nav class="rf-d2-rail">${[['trips','T','Trips'],['archive','A','Archive'],['account','Y','You']].map(([key,glyph,label])=>`<button class="rf-d2-rail-item ${STATE.tab===key?'is-active':''}" data-action="rf-d2-nav" data-tab="${key}" type="button"><span class="rf-d2-rail-glyph">${glyph}</span><span class="rf-d2-rail-label">${label}</span></button>`).join('')}</nav><div class="rf-d2-sidebar-spacer"></div><div class="rf-d2-lifetime"><div class="rf-d2-lifetime-kicker">Lifetime</div><div class="rf-d2-lifetime-row"><span>${l.trips}</span><span>${Math.round(l.distance).toLocaleString()}</span></div><div class="rf-d2-lifetime-labels"><span>Trips</span><span>km</span></div></div><div class="rf-d2-user"><span class="rf-d2-user-avatar">${esc(initials())}</span><span class="rf-d2-user-meta"><strong>${esc(userName())}</strong></span></div></aside>`; }
function renderTripList(selected) { return `<aside class="rf-d2-trips-col"><div class="rf-d2-trips-head"><div><div class="rf-d2-kicker">The road map</div><h1 class="rf-d2-col-title">Trips</h1><div class="rf-d2-col-sub">${activeTrips().length} on the road map · ${archiveTrips().length} in archive</div></div><button class="rf-d2-btn is-primary" data-action="rf-d2-new-trip" type="button">+ New</button></div><div class="rf-d2-filter-row">${filters(TRIP_FILTERS, STATE.tripStatusFilter || 'all')}${search(STATE.tripFiltersOpen || !!STATE.tripSearch, STATE.tripSearch)}</div><div class="rf-d2-master-list">${activeTrips().map(t => renderTripRow(t, selected)).join('') || '<div class="rf-d2-empty">No matching trips.</div>'}</div></aside>`; }
function renderTripRow(trip, selected) { const s = stats(trip); return `<button class="rf-d2-trip-row ${selected === trip.id ? 'is-selected' : ''}" data-action="rf-d2-select-trip" data-trip-id="${esc(trip.id)}" type="button"><div class="rf-d2-trip-row-no">${esc(tripNo(trip))}</div><div class="rf-d2-trip-row-title">${esc(trip.title || 'Untitled trip')}</div><div class="rf-d2-trip-row-sub">${esc(subtitle(trip))}</div><div class="rf-d2-trip-row-meta"><span>${esc(fmtDateRange(trip.start_date, trip.end_date))}</span><span>${Math.round(s.distance).toLocaleString()} km</span><span>${s.stages} st</span></div>${statePill(trip.status)}</button>`; }
function renderLanding() { const trip = activeTrips()[0]; return `<main class="rf-d2-main">${trip ? hero(trip,{withStats:true,withRoute:true}) : '<div class="rf-d2-empty-card">No trips yet.</div>'}<div class="rf-d2-hint">Click a trip on the left to open it. The trip expands into stages and a detail pane.</div></main>`; }
function renderTripView(trip) { const view = tripView(); if (view === 'summary') return renderSummary(trip); if (view === 'costs') return renderCosts(trip); if (view === 'items') return renderItems(trip); return renderStages(trip); }
function renderStages(trip) { const raw = rawStages(trip.id); if (raw === 'loading' || STATE.stagesLoading) return `<main class="rf-d2-main">${hero(trip,{withStats:true,withRoute:true})}${tabs('stages')}${loadingHtml('Loading stages…')}</main><aside class="rf-d2-aside">${loadingHtml('Loading detail…')}</aside>`; const st = stages(trip.id); const selected = st.find(stage => stage.id === STATE.selectedStageId) || st[0]; return `<main class="rf-d2-main">${hero(trip,{withStats:true,withRoute:true})}${tabs('stages')}<div class="rf-d2-section-head"><div class="rf-d2-section-title">${st.length} stages</div><button class="rf-d2-btn is-primary" data-action="rf-d2-add-stage" type="button">+ Add stage</button></div><div class="rf-d2-stage-list">${st.map((stage,i)=>renderStageRow(stage,i,selected?.id)).join('')}<button class="rf-d2-btn is-dashed" data-action="rf-d2-add-stage" type="button">+ Add another stage</button></div></main>${renderAside(trip,selected)}`; }
function renderStageRow(stage, index, selectedId) { return `<button class="rf-d2-stage-row ${selectedId === stage.id ? 'is-selected' : ''}" data-action="rf-d2-select-stage" data-stage-id="${esc(stage.id)}" type="button"><div class="rf-d2-stage-no-col"><div class="rf-d2-stage-no">${index + 1}</div><div class="rf-d2-stage-rule"></div><div class="rf-d2-stage-day">${esc(day(stage.planned_date))}</div></div><div class="rf-d2-stage-body"><div class="rf-d2-stage-row-head"><div class="rf-d2-stage-title">${esc(stage.start_location || 'Start')} <span class="rf-d2-stage-to">to</span> ${esc(stage.end_location || 'End')}</div></div><div class="rf-d2-stage-high">${esc(stage.notes || '')}</div><div class="rf-d2-stage-mono"><span><span class="rf-d2-stage-mono-label">dist</span> ${Math.round(Number(stage.distance_km) || 0)}km</span><span>${esc(fmtDate(stage.planned_date) || '')}</span></div></div></button>`; }
function renderAside(trip, stage) { if (STATE.wizard === 'stage') return renderStageWizard(trip); if (STATE.wizard === 'journal') return renderJournalWizard(); if (!stage) return '<aside class="rf-d2-aside"><div class="rf-d2-empty">Select a stage.</div></aside>'; const rawEntries = STATE.entriesByStage[stage.id]; const entries = arr(rawEntries); const stageExpenses = expenses(trip.id).filter(e => e.stage_id === stage.id); return `<aside class="rf-d2-aside"><div class="rf-d2-aside-head"><div class="rf-d2-aside-kicker">Stage ${esc(stage.order_index || '')} · ${esc(fmtDate(stage.planned_date) || '')}</div><h2 class="rf-d2-aside-title">${esc(stage.start_location || 'Start')} <span style="font-style:italic;color:var(--rf-d2-muted)">to</span> ${esc(stage.end_location || 'End')}</h2><div class="rf-d2-aside-sub">${esc(stage.notes || '')}</div></div><div class="rf-d2-sky"><div class="rf-d2-sky-tag">Sky advisory</div><div class="rf-d2-sky-grid"><div>Start<br>☁️<br>—</div><div>Midpoint<br>🌤️<br>—</div><div>End<br>🌧️<br>—</div></div></div><div class="rf-d2-section-head"><div class="rf-d2-section-title">The day's notes</div><button class="rf-d2-btn is-primary" data-action="rf-d2-add-journal" type="button">+ Add</button></div>${rawEntries === 'loading' ? loadingHtml('Loading notes…') : entries.map(entryHtml).join('') || '<div class="rf-d2-mini-table">No entries yet.</div>'}<div class="rf-d2-section-head"><div class="rf-d2-section-title">Stage costs</div><button class="rf-d2-btn is-primary" data-action="rf-v2-add-stage-expense" data-stage-id="${esc(stage.id)}" type="button">+ Add</button></div><div class="rf-d2-mini-table">${stageExpenses.map(expenseMini).join('') || 'No costs assigned to this stage.'}</div></aside>`; }
function entryHtml(entry, index) { const time = entry.timestamp ? new Date(entry.timestamp).toLocaleTimeString([], { hour:'2-digit', minute:'2-digit' }) : ''; return `<div class="rf-d2-entry"><div class="rf-d2-entry-bullet">${index + 1}</div><div><div class="rf-d2-entry-head"><div class="rf-d2-entry-type">A ${esc(entry.entry_type || 'note')}</div><div class="rf-d2-entry-when">${esc(time)}</div></div><div class="rf-d2-entry-title">${esc(entry.title || 'Untitled')}</div><div class="rf-d2-entry-loc">${entry.location ? `at ${esc(entry.location)}` : ''}</div></div></div>`; }
function expenseMini(expense) { return `<div class="rf-d2-mini-table-row"><div><div class="rf-d2-mini-cat">${esc(categoryLabel(expense.category))}</div><div class="rf-d2-mini-meta">${esc(payerName(expense.user_id))}</div></div><div>${esc(fmtEuro(expense.amount || 0))}</div></div>`; }
function renderStageWizard(trip) { return `<aside class="rf-d2-aside"><div class="rf-d2-aside-head"><div class="rf-d2-aside-kicker">New stage</div><h2 class="rf-d2-aside-title">Add a stage</h2></div><input class="rf-d2-input" id="v2-stage-from" placeholder="From"><input class="rf-d2-input" id="v2-stage-to" placeholder="To"><input class="rf-d2-input" id="v2-stage-date" type="date" value="${esc(trip.start_date || '')}"><input class="rf-d2-input" id="v2-stage-km" inputmode="decimal" placeholder="Distance km"><textarea class="rf-d2-textarea" id="v2-stage-notes" placeholder="Notes"></textarea><div class="rf-d2-form-actions"><button class="rf-d2-btn" data-action="rf-d2-cancel-wizard">Cancel</button><button class="rf-d2-btn is-primary" data-action="rf-d2-save-stage">Save stage</button></div></aside>`; }
function renderJournalWizard() { return `<aside class="rf-d2-aside"><div class="rf-d2-aside-head"><div class="rf-d2-aside-kicker">New entry</div><h2 class="rf-d2-aside-title">A note from the road</h2></div><input class="rf-d2-input" id="v2-entry-title" placeholder="Title"><input class="rf-d2-input" id="v2-entry-place" placeholder="Place"><input class="rf-d2-input" id="v2-entry-time" type="time"><textarea class="rf-d2-textarea" id="v2-entry-note" placeholder="What happened here?"></textarea><div class="rf-d2-form-actions"><button class="rf-d2-btn" data-action="rf-d2-cancel-wizard">Cancel</button><button class="rf-d2-btn is-primary" data-action="rf-d2-save-journal">Save entry</button></div></aside>`; }
function renderSummary(trip) { const s = stats(trip); return `<main class="rf-d2-main is-wide">${hero(trip)}${tabs('summary')}${route(trip)}<div class="rf-d2-section-title">By stage</div>${summaryTable(trip)}<div class="rf-d2-total-strip"><div><span>Total distance</span><strong>${Math.round(s.distance).toLocaleString()} km</strong></div><div><span>Total spent</span><strong>${fmtEuro(s.spent)}</strong></div><div><span>Journal</span><strong>${s.entries} entries</strong></div></div></main>`; }
function summaryTable(trip) { const rows = stages(trip.id).map((stage,i)=>{ const entries = arr(STATE.entriesByStage[stage.id]); return `<div class="rf-clean-table-row"><span>${i+1}</span><strong>${esc(stage.start_location || 'Start')} to ${esc(stage.end_location || 'End')}</strong><span>${esc(fmtDate(stage.planned_date) || '—')}</span><span>${Math.round(Number(stage.distance_km) || 0)} km</span><span>${esc(stage.notes || '—')}</span></div>${entries.map((entry,j)=>`<div class="rf-clean-summary-entry"><span></span><strong>${j+1}. ${esc(entry.title || 'Untitled entry')}</strong><span>${entry.timestamp ? esc(new Date(entry.timestamp).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})) : '—'}</span><span>${esc(entry.entry_type || 'note')}</span><span>${esc(entry.location || entry.description || 'Journal entry')}</span></div>`).join('')}`; }).join(''); return `<div class="rf-clean-table"><div class="rf-clean-table-head"><span>Stage</span><span>Route / journal</span><span>Date / time</span><span>Distance / type</span><span>Notes / place</span></div>${rows || '<div class="rf-d2-empty">No stages yet.</div>'}</div>`; }
function renderCosts(trip) { const ex = expenses(trip.id); const agg = aggregateExpense(ex); return `<main class="rf-d2-main">${hero(trip)}${tabs('costs')}<div class="rf-d2-ledger-hero"><div><div class="rf-d2-ledger-label">The trip ledger</div><div class="rf-d2-ledger-value">${fmtEuro(agg.total)}</div>${stamp(`${ex.length} entries`)}</div><button class="rf-d2-btn is-primary" data-action="rf-v2-add-expense" type="button">+ Log expense</button></div><div class="rf-d2-table">${ex.map(expenseRow).join('') || '<div class="rf-d2-empty">No costs yet.</div>'}</div></main><aside class="rf-d2-aside"><div class="rf-d2-section-title">By category</div>${breakdown(agg.cat)}<div class="rf-d2-section-title">By payer</div>${breakdown(agg.payer)}</aside>`; }
function expenseRow(expense) { return `<div class="rf-d2-table-row"><div>${esc(categoryLabel(expense.category))}</div><div>${esc(payerName(expense.user_id))}</div><div>${esc(fmtDate(expense.date) || '')}</div><div>${fmtEuro(expense.amount || 0)}</div><div class="rf-v2-expense-actions"><button class="rf-d2-btn" data-action="rf-v2-edit-expense" data-expense-id="${esc(expense.id)}">Edit</button><button class="rf-d2-btn is-danger" data-action="rf-v2-delete-expense" data-expense-id="${esc(expense.id)}">Delete</button></div></div>`; }
function breakdown(map) { return `<div class="rf-d2-breakdown">${[...map.entries()].map(([label,amount])=>`<div class="rf-d2-break-row"><span>${esc(label)}</span><strong>${fmtEuro(amount)}</strong></div>`).join('') || '<div class="rf-d2-break-row"><span>No data</span><strong>—</strong></div>'}</div>`; }
function renderItems(trip) { const raw = rawItems(trip.id); if (raw === 'loading' || STATE.itemsLoading) return `<main class="rf-d2-main">${hero(trip)}${tabs('items')}${loadingHtml('Loading items…')}</main><aside class="rf-d2-aside">${loadingHtml('Loading category…')}</aside>`; const all = items(trip.id); const cs = categories(trip.id); const selected = STATE.selectedCategoryKey || slug(cs[0]?.name); const group = all.filter(item => slug(item.category?.name || item.category_name || 'Other') === selected && ((STATE.itemStatusFilter || 'all') === 'all' || item.status === STATE.itemStatusFilter)); return `<main class="rf-d2-main">${hero(trip)}${tabs('items')}<div class="rf-d2-items-hero"><div class="rf-d2-ledger-label">The packing list</div><div class="rf-d2-items-big">${all.filter(item=>item.status==='packed').length} <span>of ${all.length} packed</span></div><button class="rf-d2-btn is-primary" data-action="rf-d2-add-item" type="button">+ Add item</button></div><div class="rf-d2-section-head"><div class="rf-d2-section-title">Categories</div></div><div class="rf-d2-item-cats">${cs.map((cat,i)=>itemCatRow(cat,i,selected,all)).join('')}</div></main><aside class="rf-d2-aside"><div class="rf-d2-aside-head"><div class="rf-d2-aside-kicker">Category</div><h2 class="rf-d2-aside-title">${esc(cs.find(cat => slug(cat.name) === selected)?.name || 'Items')}</h2></div>${filters(ITEM_FILTERS, STATE.itemStatusFilter || 'all', 'item-filter')}<div class="rf-d2-item-list">${group.map(itemRow).join('') || '<div class="rf-d2-empty">No items here.</div>'}</div>${STATE.wizard === 'item' ? itemForm(cs) : ''}</aside>`; }
function itemCatRow(cat, index, selected, all) { const key = slug(cat.name); const group = all.filter(item => slug(item.category?.name || item.category_name || 'Other') === key); const packed = group.filter(item => item.status === 'packed').length; return `<button class="rf-d2-item-cat-row ${key === selected ? 'is-selected' : ''}" data-action="rf-d2-select-category" data-category="${esc(key)}" type="button"><span>${index+1}</span><strong>${esc(cat.name)}</strong><span class="rf-d2-item-progress"><i style="width:${group.length ? Math.round((packed/group.length)*100) : 0}%"></i></span><span>${packed}/${group.length} packed</span><span>›</span></button>`; }
function itemRow(item) { return `<div class="rf-d2-item-row ${item.status === 'packed' ? 'is-packed' : ''}"><button class="rf-d2-item-check" data-action="rf-d2-toggle-item" data-item-id="${esc(item.id)}" type="button">${item.status === 'packed' ? '✓' : ''}</button><div><strong>${esc(item.name)}</strong>${item.notes ? `<small>${esc(item.notes)}</small>` : ''}</div><span class="rf-d2-item-chip is-${esc(item.status || 'planned')}"><span class="dot"></span>${esc(item.status || 'planned')}</span></div>`; }
function itemForm(cs) { return `<form class="rf-d2-quick-form" data-action="rf-d2-item-form"><input class="rf-d2-input" name="text" placeholder="e.g. Rain gloves"><select class="rf-d2-input" name="category_id">${cs.map(cat=>`<option value="${esc(cat.id || '')}">${esc(cat.name)}</option>`).join('')}</select><button class="rf-d2-btn is-primary" type="submit">Add item</button></form>`; }
function renderArchive() { const selected = STATE.selectedArchiveTripId ? STATE.trips.find(t => t.id === STATE.selectedArchiveTripId) : null; if (selected) return `<main class="rf-d2-main is-wide rf-clean-archive-detail">${hero(selected,{withStats:true,backAction:'rf-d2-back-to-archive'})}<div class="rf-d2-section-title">Archive summary</div>${summaryTable(selected)}</main>`; const rows = archiveTrips(); const l = lifetime(); return `<main class="rf-d2-main is-archive"><div class="rf-d2-kicker">The collection</div><h1 class="rf-d2-hero-title">Archive</h1><div class="rf-d2-hero-sub">${rows.filter(t=>t.status==='completed').length} put to bed · ${rows.filter(t=>t.status==='cancelled').length} called off</div><div class="rf-d2-filter-row">${filters(ARCHIVE_FILTERS, STATE.archiveStatusFilter || 'all')}${search(STATE.archiveFiltersOpen || !!STATE.archiveSearch, STATE.archiveSearch)}</div>${STATE.archiveDataLoading ? loadingHtml('Loading archive totals…') : ''}<div class="rf-d2-archive-totals"><h2>Lifetime totals</h2><div>Completed <strong>${l.completed}</strong></div><div>Distance <strong>${Math.round(l.distance).toLocaleString()}</strong></div><div>Spent <strong>${fmtEuro(l.spent)}</strong></div><div>Notes <strong>${l.entries}</strong></div></div><div class="rf-d2-section-head"><div class="rf-d2-section-title">The geography</div>${stamp('Heatmap')}</div><div class="rf-d2-map-card"><div class="rf-v2-archive-map" id="rf-v2-archive-map"></div><div class="rf-v2-archive-map-status" id="rf-v2-archive-map-status">Loading archive geography…</div></div>${rows.map(trip=>`<button class="rf-d2-archive-row" data-action="rf-d2-select-archived" data-trip-id="${esc(trip.id)}" type="button"><span>${esc(tripNo(trip))}</span><strong>${esc(trip.title || 'Untitled trip')}</strong><small>${esc(season(trip))}</small><b>${fmtEuro(stats(trip).spent)}</b></button>`).join('') || '<div class="rf-d2-empty">No archived trips.</div>'}</main>`; }
function renderAccount() { const l = lifetime(); const year = memberSinceYear(); return `<main class="rf-d2-main is-account"><section class="rf-d2-account-card"><div class="rf-d2-account-avatar">${profileAvatar()}</div><div><h1>${esc(userName())}</h1><em>${year ? `Routefolk member since ${year}` : 'Routefolk member'}</em></div><button class="rf-d2-btn is-danger" data-action="rf-d2-sign-out">Sign out</button></section><section class="rf-d2-riders-card"><h2>Other riders</h2><p>${Math.max(0, STATE.profiles.length - 1)} people you've ridden with</p></section><section class="rf-d2-mileage"><h2>Mileage to date</h2><div><strong>${l.trips}</strong><span>Trips</span></div><div><strong>${Math.round(l.distance).toLocaleString()}</strong><span>Distance</span></div><div><strong>${l.days}</strong><span>Days</span></div><div><strong>${fmtEuro(l.spent)}</strong><span>Spent</span></div></section><section class="rf-clean-desktop-pref">${palettePanel()}</section><div class="rf-d2-version">routefolk · v0.6.2</div></main>`; }
