// ============================================================
// routefolk — state/app-state.js
// Shared mutable app state.
// Phase 22: selectedStageId + detail tab views.
// ============================================================

export const STATE = {
  tab: 'trips',
  view: 'list', // list | detail | summary | costs | packing
  viewTripId: null,
  selectedStageId: null,
  user: null,
  appAccess: null,
  accessLoading: false,
  accessError: null,
  schemaVersion: null,
  schemaLoading: false,
  schemaError: null,
  trips: [],
  tripsLoading: false,
  tripsError: null,
  stagesByTrip: {},
  stagesLoading: false,
  stagesError: null,
  forecastsByStage: {},
  entriesByStage: {},
  expandedStages: new Set(),
  expandedGpxStages: new Set(),
  expandedSummaryStages: new Set(),
  profiles: [],
  profilesById: {},
  profilesLoading: false,
  profilesError: null,
  expensesByTrip: {},
  gpxByTrip: {},
  gpxGeometryByTrack: {},
  gpxLoading: false,
  gpxError: null,
  archiveGpxLoading: false,
  archiveGpxError: null,
  expensesLoading: false,
  expensesError: null,
  itemsByTrip: {},
  itemCategoriesByTrip: {},
  itemsLoading: false,
  itemsError: null,
  tripSearch: '',
  tripStatusFilter: 'all',
  tripFiltersOpen: false,
  archiveSearch: '',
  archiveStatusFilter: 'all',
  archiveFiltersOpen: false,
  archiveViewMode: 'list',
  archiveMapLayer: 'heatmap',
  archiveDataLoading: false,
  archiveDataError: null,
  isOnline: typeof navigator === 'undefined' ? true : navigator.onLine !== false,
};
