// ============================================================
// routefolk — state/app-state.js
// Shared mutable app state.
// ============================================================

export const STATE = {
  tab: 'trips',
  view: 'list', // list | detail | summary | costs | packing | journal
  viewTripId: null,
  selectedTripId: null,
  selectedArchiveTripId: null,
  selectedStageId: null,
  // Route Atlas: which stage card has its ↑↓ Edit Delete Journal row
  // revealed on the mobile Stages list — hidden by default, one card at
  // a time, distinct from selectedStageId (which drives journal/aside
  // context elsewhere and stays selected across screens).
  stageListSelectedId: null,
  selectedEntryId: null,
  selectedCategoryKey: null,
  lastTripView: 'detail',
  lastArchiveView: 'list',
  wizard: null, // null | trip | trip-edit | stage | stage-edit | journal | journal-edit | gpx-upload | expense | item | road | road-edit
  editTargetId: null,
  gpxUploadTarget: null,
  journalType: 'note',
  navSheet: null,
  user: null,
  appAccess: null,
  accessLoading: false,
  accessError: null,
  schemaVersion: null,
  schemaLoading: false,
  schemaError: null,
  trips: [],
  tripsLoading: false,
  tripsError: null,
  stagesByTrip: {},
  stagesLoading: false,
  stagesError: null,
  forecastsByStage: {},
  entriesByStage: {},
  expandedStages: new Set(),
  expandedGpxStages: new Set(),
  expandedSummaryStages: new Set(),
  profiles: [],
  profilesById: {},
  profilesLoading: false,
  profilesError: null,
  selectableTripMembers: [],
  selectableTripMembersLoading: false,
  selectableTripMembersError: null,
  tripMembersByTrip: {},
  tripMembersLoadingByTrip: {},
  tripMembersErrorByTrip: {},
  expensesByTrip: {},
  gpxByTrip: {},
  gpxGeometryByTrack: {},
  gpxLoading: false,
  gpxError: null,
  archiveGpxLoading: false,
  archiveGpxError: null,
  expensesLoading: false,
  expensesError: null,
  itemsByTrip: {},
  itemCategoriesByTrip: {},
  itemsLoading: false,
  itemsError: null,
  itemStatusFilter: 'all',
  tripSearch: '',
  tripStatusFilter: 'all',
  tripFiltersOpen: false,
  archiveSearch: '',
  archiveStatusFilter: 'all',
  archiveFiltersOpen: false,
  archiveViewMode: 'list',
  archiveMapLayer: 'heatmap',
  archiveDataLoading: false,
  archiveDataError: null,
  // Roads (Account/You "My roads" — HANDOFF.md): shared road log, but
  // "My roads" only ever shows the current user's own starred roads,
  // sorted by their own rating. myRoads carries each road's my_rating
  // (the viewer's own rating) already joined in by lib/roads.js.
  myRoads: [],
  myRoadsLoading: false,
  myRoadsError: null,
  roadStageLinksByRoad: {},
  isOnline: typeof navigator === 'undefined' ? true : navigator.onLine !== false,
};
