// ============================================================
// routefolk — state/app-state.js
// Shared mutable app state.
// ============================================================

export const STATE = {
  tab: 'trips',
  view: 'list', // list | detail | summary | costs | packing | journal
  viewTripId: null,
  selectedTripId: null,
  selectedArchiveTripId: null,
  selectedStageId: null,
  selectedEntryId: null,
  selectedCategoryKey: null,
  lastTripView: 'detail',
  lastArchiveView: 'list',
  wizard: null, // null | trip | trip-edit | stage | stage-edit | journal | journal-edit | gpx-upload | expense | item
  editTargetId: null,
  gpxUploadTarget: null,
  journalType: 'note',
  navSheet: null,
  user: null,
  appAccess: null,
  accessLoading: false,
  accessError: null,
  schemaVersion: null,
  schemaLoading: false,
  schemaError: null,
  trips: [],
  tripsLoading: false,
  tripsError: null,
  stagesByTrip: {},
  stagesLoading: false,
  stagesError: null,
  forecastsByStage: {},
  entriesByStage: {},
  expandedStages: new Set(),
  expandedGpxStages: new Set(),
  expandedSummaryStages: new Set(),
  profiles: [],
  profilesById: {},
  profilesLoading: false,
  profilesError: null,
  selectableTripMembers: [],
  selectableTripMembersLoading: false,
  selectableTripMembersError: null,
  tripMembersByTrip: {},
  tripMembersLoadingByTrip: {},
  tripMembersErrorByTrip: {},
  expensesByTrip: {},
  gpxByTrip: {},
  gpxGeometryByTrack: {},
  gpxLoading: false,
  gpxError: null,
  archiveGpxLoading: false,
  archiveGpxError: null,
  expensesLoading: false,
  expensesError: null,
  itemsByTrip: {},
  itemCategoriesByTrip: {},
  itemsLoading: false,
  itemsError: null,
  itemStatusFilter: 'all',
  tripSearch: '',
  tripStatusFilter: 'all',
  tripFiltersOpen: false,
  archiveSearch: '',
  archiveStatusFilter: 'all',
  archiveFiltersOpen: false,
  archiveViewMode: 'list',
  archiveMapLayer: 'heatmap',
  archiveDataLoading: false,
  archiveDataError: null,
  isOnline: typeof navigator === 'undefined' ? true : navigator.onLine !== false,
};
