export const RESOURCES = {
  trips: {
    table: 'trips',
    fields: {
      title: { type: 'string', required: true },
      description: { type: 'string' },
      start_date: { type: 'string', format: 'date' },
      end_date: { type: 'string', format: 'date' },
      cover_photo_url: { type: 'string' },
      status: { type: 'string', enum: ['planning', 'active', 'completed', 'cancelled'] },
      visibility: { type: 'string', enum: ['private', 'group'] },
    },
  },
  stages: {
    table: 'stages',
    fields: {
      trip_id: { type: 'string', format: 'uuid', required: true },
      order_index: { type: 'integer' },
      title: { type: 'string' },
      start_location: { type: 'string' },
      start_lat: { type: 'number' },
      start_lng: { type: 'number' },
      end_location: { type: 'string' },
      end_lat: { type: 'number' },
      end_lng: { type: 'number' },
      planned_date: { type: 'string', format: 'date' },
      gmaps_url: { type: 'string' },
      custom_route_url: { type: 'string' },
      distance_km: { type: 'number' },
      notes: { type: 'string' },
    },
  },
  'journal-entries': {
    table: 'journal_entries',
    fields: {
      stage_id: { type: 'string', format: 'uuid', required: true },
      entry_type: { type: 'string', enum: ['stop', 'meal', 'lodging', 'note', 'drink', 'other'] },
      title: { type: 'string' },
      description: { type: 'string' },
      location: { type: 'string' },
      location_url: { type: 'string' },
      info_url: { type: 'string' },
      timestamp: { type: 'string', format: 'date-time' },
      photo_album_url: { type: 'string' },
    },
  },
  expenses: {
    table: 'expenses',
    fields: {
      trip_id: { type: 'string', format: 'uuid', required: true },
      stage_id: { type: 'string', format: 'uuid' },
      user_id: { type: 'string', format: 'uuid' },
      category: { type: 'string', enum: ['fuel', 'food_drinks', 'lodging', 'tolls', 'parking', 'other'] },
      amount: { type: 'number', required: true },
      currency: { type: 'string', enum: ['EUR'] },
      description: { type: 'string' },
      date: { type: 'string', format: 'date' },
    },
  },
  items: {
    table: 'trip_items',
    fields: {
      trip_id: { type: 'string', format: 'uuid', required: true },
      category_id: { type: 'string', format: 'uuid' },
      name: { type: 'string', required: true },
      status: { type: 'string', enum: ['planned', 'packed', 'optional'] },
      assigned_to: { type: 'string', format: 'uuid' },
      notes: { type: 'string' },
      sort_order: { type: 'integer' },
    },
  },
  'item-categories': {
    table: 'item_categories',
    fields: {
      trip_id: { type: 'string', format: 'uuid', required: true },
      name: { type: 'string', required: true },
      sort_order: { type: 'integer' },
    },
  },
};
