// ============================================================
// routefolk — screens/v2/v2-app.js
// Designer v2 render takeover mapped to existing STATE/data.
// This module owns the visual shell while legacy app.js keeps
// auth/session/data bootstrapping active during the migration.
// ============================================================

import { STATE } from '../../state/app-state.js';
import { esc } from '../../utils/dom.js';
import { fmtDate, fmtDateRange } from '../../utils/datetime.js';
import { fmtEuro } from '../../utils/format.js';
import { userDisplayName, userInitials, initialsFromName, displayNameForUserId } from '../../utils/user.js';
import { STATUS_META, EXPENSE_CATEGORY_META } from '../../constants/app-constants.js';
import { createStage } from '../../lib/stages.js';
import { createEntry } from '../../lib/journal.js';
import { createTripItem, toggleTripItemPacked, deleteTripItem } from '../../lib/items.js';

const TRIP_FILTERS = [{key:'all',label:'All'},{key:'planning',label:'Planning'},{key:'active',label:'Active'}];
const ARCHIVE_FILTERS = [{key:'all',label:'All'},{key:'completed',label:'Completed'},{key:'cancelled',label:'Cancelled'}];
const DETAIL_TABS = [{key:'stages',label:'Stages'},{key:'summary',label:'Summary'},{key:'costs',label:'Costs'},{key:'items',label:'Items'}];
const ITEM_FILTERS = [{key:'all',label:'All'},{key:'planned',label:'Planned'},{key:'packed',label:'Packed'},{key:'optional',label:'Optional'}];
const DEFAULT_CATS = ['Clothing','Luggage','Tools & spares','Filming & gear','Chargers & power','Documents','First aid','Other essentials'];
const REFRESH_MS = 900;
let started = false;
let lastMarkup = '';
let refreshTimer = null;

function $(id){return document.getElementById(id);}
function currentTripId(){return STATE.viewTripId || STATE.selectedTripId || null;}
function currentTrip(){return STATE.trips.find((trip)=>trip.id===currentTripId()) || null;}
function stages(tripId){const rows=STATE.stagesByTrip[tripId];return Array.isArray(rows)?rows:[];}
function expenses(tripId){const rows=STATE.expensesByTrip[tripId];return Array.isArray(rows)?rows:[];}
function items(tripId){const rows=STATE.itemsByTrip[tripId];return Array.isArray(rows)?rows:[];}
function cats(tripId){const rows=STATE.itemCategoriesByTrip[tripId];return Array.isArray(rows)&&rows.length?rows:DEFAULT_CATS.map((name,i)=>({id:'',name,sort_order:i}));}
function tripView(){if(STATE.view==='summary')return'summary';if(STATE.view==='costs')return'costs';if(STATE.view==='packing')return'items';if(STATE.view==='journal')return'journal';return'stages';}
function viewForTab(key){return key==='summary'?'summary':key==='costs'?'costs':key==='items'?'packing':'detail';}
function slug(v){return String(v||'').toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'other';}
function tripNo(trip){const i=Math.max(0,STATE.trips.findIndex((x)=>x.id===trip?.id));return`No. ${String(i+1).padStart(2,'0')}`;}
function season(trip){const d=trip?.start_date?new Date(`${trip.start_date}T00:00:00Z`):null;const y=d&&!Number.isNaN(d.getTime())?d.getUTCFullYear():new Date().getFullYear();const m=d&&!Number.isNaN(d.getTime())?d.getUTCMonth():2;const s=m<=1||m===11?'Winter':m<=4?'Spring':m<=7?'Summer':'Autumn';return`${s} ${y}`;}
function sub(trip){return trip?.description||fmtDateRange(trip?.start_date,trip?.end_date)||'A new road journal';}
function stats(trip){const st=stages(trip.id);const ex=expenses(trip.id);const entries=st.reduce((sum,s)=>{const e=STATE.entriesByStage[s.id];return sum+(Array.isArray(e)?e.length:0);},0);const distance=st.reduce((sum,s)=>sum+(Number(s.distance_km)||0),0)||Number(trip.distance_km)||0;const spent=ex.reduce((sum,e)=>sum+(Number(e.amount)||0),0);return{stages:st.length,entries,distance,spent};}
function statusName(status){return STATUS_META[status]?.label||String(status||'Planning');}
function day(date){if(!date)return'';try{return new Date(`${date}T00:00:00Z`).toLocaleDateString('en-GB',{weekday:'short'}).slice(0,3);}catch{return'';}}
function lifetime(){let distance=0,spent=0,entries=0,days=0,completed=0;STATE.trips.forEach((trip)=>{if(trip.status==='completed')completed++;const st=stages(trip.id);const ex=expenses(trip.id);distance+=st.reduce((s,x)=>s+(Number(x.distance_km)||0),0)||Number(trip.distance_km)||0;spent+=ex.reduce((s,x)=>s+(Number(x.amount)||0),0);entries+=st.reduce((s,x)=>{const e=STATE.entriesByStage[x.id];return s+(Array.isArray(e)?e.length:0);},0);days+=st.length||dateSpan(trip.start_date,trip.end_date);});return{trips:STATE.trips.length,completed,distance,spent,entries,days};}
function dateSpan(start,end){if(!start||!end)return 0;const a=new Date(`${start}T00:00:00Z`);const b=new Date(`${end}T00:00:00Z`);return Number.isNaN(a.getTime())||Number.isNaN(b.getTime())?0:Math.max(1,Math.round((b-a)/86400000)+1);}
function activeTrips(){const q=(STATE.tripSearch||'').trim().toLowerCase();const f=STATE.tripStatusFilter||'all';return STATE.trips.filter((t)=>['planning','active'].includes(t.status)).filter((t)=>(f==='all'||t.status===f)&&(!q||`${t.title||''} ${t.description||''}`.toLowerCase().includes(q)));}
function archiveTrips(){const q=(STATE.archiveSearch||'').trim().toLowerCase();const f=STATE.archiveStatusFilter||'all';return STATE.trips.filter((t)=>['completed','cancelled'].includes(t.status)).filter((t)=>(f==='all'||t.status===f)&&(!q||`${t.title||''} ${t.description||''}`.toLowerCase().includes(q)));}
function statePill(status,ns='rf-d2'){return`<span class="${ns}-state-pill is-${esc(status||'planning')}"><span class="${ns}-state-dot"></span>${esc(statusName(status))}</span>`;}
function stamp(text,kind='primary',ns='rf-d2'){return`<span class="${ns}-stamp is-${esc(kind)}">${esc(text)}</span>`;}
function avatar(name,ns='rf-d2'){return`<span class="${ns}-avatar">${esc(initialsFromName(name||'RF'))}</span>`;}
function filters(items,active,ns='rf-d2',action='status-filter'){return`<div class="${ns}-pills">${items.map((it)=>`<button class="${ns}-pill ${active===it.key?'is-active':''}" data-action="${ns}-${action}" data-value="${esc(it.key)}" type="button">${esc(it.label)}</button>`).join('')}</div>`;}
function search(open,value,ns='rf-d2'){if(!open)return`<button class="${ns}-search-btn" data-action="${ns}-search-toggle" type="button" aria-label="Search"><svg width="13" height="13" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.4"><circle cx="7" cy="7" r="5"/><line x1="11" y1="11" x2="14.5" y2="14.5" stroke-linecap="round"/></svg></button>`;return`<div class="${ns}-search"><input type="search" data-action="${ns}-search-input" value="${esc(value||'')}" placeholder="Search by name"><button class="${ns}-search-close" data-action="${ns}-search-toggle" type="button">×</button></div>`;}
function tabs(active,ns='rf-d2'){return`<nav class="${ns}-selector-tabs">${DETAIL_TABS.map((t)=>`<button class="${ns}-selector-tab ${active===t.key?'is-active':''}" data-action="${ns}-tab" data-value="${t.key}" type="button">${t.label}</button>`).join('')}</nav>`;}
function route(trip,ns='rf-d2'){const st=stages(trip.id);const from=st[0]?.start_location||'Start';const to=st[st.length-1]?.end_location||'End';return`<div class="${ns}-route"><div class="${ns}-route-labels"><span>${esc(from)}</span><span>${esc(to)}</span></div><svg viewBox="0 0 780 120"><path d="M48 80 C150 36 250 92 355 58 S535 46 724 74"></path>${[48,188,328,468,608,724].map((x,i)=>`<circle cx="${x}" cy="${i===0?80:i===5?74:66}" r="5"/>`).join('')}</svg></div>`;}
function hero(trip,{withStats=false,withRoute=false}={}){const s=stats(trip);return`<header class="rf-d2-hero"><div class="rf-d2-hero-top"><div><button class="rf-d2-back" data-action="rf-d2-back-to-trips" type="button">← Trips</button><div class="rf-d2-kicker">${esc(tripNo(trip))} · ${esc(season(trip))}</div><h1 class="rf-d2-hero-title">${esc(trip.title)}</h1><div class="rf-d2-hero-sub">${esc(sub(trip))}</div></div><div class="rf-d2-hero-stamps">${statePill(trip.status)}${stamp('Group','accent')}</div></div>${withStats?`<div class="rf-d2-stat-grid"><div><span>Distance</span><strong>${Math.round(s.distance).toLocaleString()}</strong><small>km recorded</small></div><div><span>Spent</span><strong>${fmtEuro(s.spent)}</strong><small>so far</small></div><div><span>Stages</span><strong>${s.stages}</strong><small>days</small></div><div><span>Entries</span><strong>${s.entries}</strong><small>journal</small></div></div>`:''}${withRoute?route(trip):''}</header>`;}

function desktop(){const trip=currentTrip();const third=STATE.tab==='trips'&&trip&&tripView()!=='summary';let body='';if(STATE.tab==='archive')body=dArchive();else if(STATE.tab==='account')body=dAccount();else if(!trip)body=dTripList(null)+dLanding();else body=dTripList(trip.id)+dTripView(trip);return`<div class="rf-d2-app ${third?'is-3-pane':''}">${dSidebar(third)}${body}${dCommand()}</div>`;}
function dSidebar(collapsed){const l=lifetime();return`<aside class="rf-d2-sidebar ${collapsed?'is-collapsed':''}"><div class="rf-d2-sidebar-head">${collapsed?'<div class="rf-d2-sidebar-mark">r</div><div class="rf-d2-sidebar-mark-sub">routefolk</div>':'<div class="rf-d2-sidebar-kicker">Routefolk</div><div class="rf-d2-sidebar-title">Field journal</div>'}</div><nav class="rf-d2-rail">${[['trips','T'],['archive','A'],['account','Y']].map(([k,g])=>`<button class="rf-d2-rail-item ${STATE.tab===k?'is-active':''}" data-action="rf-d2-nav" data-tab="${k}" type="button"><span class="rf-d2-rail-glyph">${g}</span><span class="rf-d2-rail-label">${k==='account'?'You':k[0].toUpperCase()+k.slice(1)}</span></button>`).join('')}</nav><div class="rf-d2-sidebar-spacer"></div><div class="rf-d2-lifetime"><div class="rf-d2-lifetime-kicker">Lifetime</div><div class="rf-d2-lifetime-row"><span>${l.trips}</span><span>${Math.round(l.distance).toLocaleString()}</span></div><div class="rf-d2-lifetime-labels"><span>Trips</span><span>km</span></div></div><div class="rf-d2-user"><span class="rf-d2-user-avatar">${esc(userInitials(STATE.user))}</span><span class="rf-d2-user-meta"><strong>${esc(userDisplayName(STATE.user))}</strong><small>${esc(STATE.user?.email||'')}</small></span></div></aside>`;}
function dTripList(selected){return`<aside class="rf-d2-trips-col"><div class="rf-d2-trips-head"><div><div class="rf-d2-kicker">The road map</div><h1 class="rf-d2-col-title">Trips</h1><div class="rf-d2-col-sub">${activeTrips().length} on the road map · ${archiveTrips().length} in archive</div></div><button class="rf-d2-btn is-primary" data-action="rf-d2-new-trip" type="button">+ New</button></div><div class="rf-d2-filter-row">${filters(TRIP_FILTERS,STATE.tripStatusFilter||'all')}${search(STATE.tripFiltersOpen||!!STATE.tripSearch,STATE.tripSearch)}</div><div class="rf-d2-master-list">${activeTrips().map((t)=>dTripRow(t,selected)).join('')||'<div class="rf-d2-empty">No matching trips.</div>'}</div></aside>`;}
function dTripRow(t,selected){const s=stats(t);return`<button class="rf-d2-trip-row ${selected===t.id?'is-selected':''}" data-action="rf-d2-select-trip" data-trip-id="${esc(t.id)}" type="button"><div class="rf-d2-trip-row-no">${esc(tripNo(t))}</div><div class="rf-d2-trip-row-title">${esc(t.title)}</div><div class="rf-d2-trip-row-sub">${esc(sub(t))}</div><div class="rf-d2-trip-row-meta"><span>${esc(fmtDateRange(t.start_date,t.end_date))}</span><span>${Math.round(s.distance).toLocaleString()} km</span><span>${s.stages} st</span></div>${statePill(t.status)}</button>`;}
function dLanding(){const t=activeTrips()[0];return`<main class="rf-d2-main">${t?hero(t,{withStats:true,withRoute:true}):'<div class="rf-d2-empty-card">No trips yet.</div>'}<div class="rf-d2-hint">Click a trip on the left to open it. The trip expands into stages and a detail pane.</div></main>`;}
function dTripView(trip){const v=tripView();if(v==='summary')return dSummary(trip);if(v==='costs')return dCosts(trip);if(v==='items')return dItems(trip);return dStages(trip);}
function dStages(trip){const st=stages(trip.id);const sel=st.find((s)=>s.id===STATE.selectedStageId)||st[0];if(sel&&!STATE.selectedStageId)STATE.selectedStageId=sel.id;return`<main class="rf-d2-main">${hero(trip,{withStats:true,withRoute:true})}${tabs('stages')}<div class="rf-d2-section-head"><div class="rf-d2-section-title">${st.length} stages · day ${Math.min(2,st.length)||1} of ${st.length||1}</div><button class="rf-d2-btn is-primary" data-action="rf-d2-add-stage" type="button">+ Add stage</button></div><div class="rf-d2-stage-list">${st.map((s,i)=>dStageRow(s,i,sel?.id)).join('')}<button class="rf-d2-btn is-dashed" data-action="rf-d2-add-stage" type="button">+ Add another stage</button></div></main>${dAside(trip,sel)}`;}
function dStageRow(s,i,selected){return`<button class="rf-d2-stage-row ${selected===s.id?'is-selected':''}" data-action="rf-d2-select-stage" data-stage-id="${esc(s.id)}" type="button"><div class="rf-d2-stage-no-col"><div class="rf-d2-stage-no">${i+1}</div><div class="rf-d2-stage-rule"></div><div class="rf-d2-stage-day">${esc(day(s.planned_date))}</div></div><div class="rf-d2-stage-body"><div class="rf-d2-stage-row-head"><div class="rf-d2-stage-title">${esc(s.start_location||'Start')} <span class="rf-d2-stage-to">to</span> ${esc(s.end_location||'End')}</div>${i===1?stamp('Today'):''}</div><div class="rf-d2-stage-high">${esc(s.notes||'')}</div><div class="rf-d2-stage-mono"><span><span class="rf-d2-stage-mono-label">dist</span> ${Math.round(Number(s.distance_km)||0)}km</span><span>${esc(fmtDate(s.planned_date)||'')}</span></div></div></button>`;}
function dAside(trip,stage){if(STATE.wizard==='stage')return dStageWizard(trip);if(STATE.wizard==='journal')return dJournalWizard(stage);if(!stage)return'<aside class="rf-d2-aside"><div class="rf-d2-empty">Select a stage.</div></aside>';const entries=STATE.entriesByStage[stage.id];const e=Array.isArray(entries)?entries:[];const ex=expenses(trip.id).filter((x)=>x.stage_id===stage.id);return`<aside class="rf-d2-aside"><div class="rf-d2-aside-head"><div class="rf-d2-aside-kicker">Stage ${esc(stage.order_index||'')} · ${esc(fmtDate(stage.planned_date)||'')}</div><h2 class="rf-d2-aside-title">${esc(stage.start_location||'Start')} <span style="font-style:italic;color:var(--rf-d2-muted)">to</span> ${esc(stage.end_location||'End')}</h2><div class="rf-d2-aside-sub">${esc(stage.notes||'')}</div></div><div class="rf-d2-sky"><div class="rf-d2-sky-tag">Sky advisory</div><div class="rf-d2-sky-grid"><div>Start<br>☁️<br>—</div><div>Midpoint<br>🌤️<br>—</div><div>End<br>🌧️<br>—</div></div></div><div class="rf-d2-section-head"><div class="rf-d2-section-title">The day's notes</div><button class="rf-d2-btn is-primary" data-action="rf-d2-add-journal" type="button">+ Add</button></div>${e.map((x,i)=>entry(x,i)).join('')||'<div class="rf-d2-mini-table">No entries yet.</div>'}<div class="rf-d2-section-head"><div class="rf-d2-section-title">Stage costs</div></div><div class="rf-d2-mini-table">${ex.map(expenseMini).join('')||'No costs assigned to this stage.'}</div></aside>`;}
function entry(e,i){const time=e.timestamp?new Date(e.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'';return`<div class="rf-d2-entry"><div class="rf-d2-entry-bullet">${i+1}</div><div><div class="rf-d2-entry-head"><div class="rf-d2-entry-type">A ${esc(e.entry_type||'note')}</div><div class="rf-d2-entry-when">${esc(time)}</div></div><div class="rf-d2-entry-title">${esc(e.title||'Untitled')}</div><div class="rf-d2-entry-loc">${e.location?'at '+esc(e.location):''}</div></div></div>`;}
function expenseMini(e){const meta=EXPENSE_CATEGORY_META[e.category]||EXPENSE_CATEGORY_META.other;return`<div class="rf-d2-mini-table-row"><div><div class="rf-d2-mini-cat">${esc(meta.label)}</div><div class="rf-d2-mini-meta">${esc(displayNameForUserId(e.user_id))}</div></div><div>${esc(fmtEuro(e.amount||0))}</div></div>`;}
function dStageWizard(trip){return`<aside class="rf-d2-aside"><div class="rf-d2-aside-head"><div class="rf-d2-aside-kicker">New stage</div><h2 class="rf-d2-aside-title">Add a stage</h2></div><input class="rf-d2-input" id="v2-stage-from" placeholder="From"><input class="rf-d2-input" id="v2-stage-to" placeholder="To"><input class="rf-d2-input" id="v2-stage-date" type="date" value="${esc(trip.start_date||'')}"><input class="rf-d2-input" id="v2-stage-km" inputmode="decimal" placeholder="Distance km"><textarea class="rf-d2-textarea" id="v2-stage-notes" placeholder="Notes"></textarea><div class="rf-d2-form-actions"><button class="rf-d2-btn" data-action="rf-d2-cancel-wizard">Cancel</button><button class="rf-d2-btn is-primary" data-action="rf-d2-save-stage">Save stage</button></div></aside>`;}
function dJournalWizard(){return`<aside class="rf-d2-aside"><div class="rf-d2-aside-head"><div class="rf-d2-aside-kicker">New entry</div><h2 class="rf-d2-aside-title">A note from the road</h2></div><input class="rf-d2-input" id="v2-entry-title" placeholder="Title"><input class="rf-d2-input" id="v2-entry-place" placeholder="Place"><input class="rf-d2-input" id="v2-entry-time" type="time"><textarea class="rf-d2-textarea" id="v2-entry-note" placeholder="What happened here?"></textarea><div class="rf-d2-form-actions"><button class="rf-d2-btn" data-action="rf-d2-cancel-wizard">Cancel</button><button class="rf-d2-btn is-primary" data-action="rf-d2-save-journal">Save entry</button></div></aside>`;}
function dSummary(trip){const s=stats(trip);return`<main class="rf-d2-main is-wide">${hero(trip)}${tabs('summary')}${route(trip)}<div class="rf-d2-section-title">By stage</div><div class="rf-d2-table">${stages(trip.id).map((x,i)=>`<div class="rf-d2-table-row"><div>${i+1}</div><div><strong>${esc(x.start_location||'')} to ${esc(x.end_location||'')}</strong><small>${esc(fmtDate(x.planned_date)||'')}</small></div><div>${Math.round(Number(x.distance_km)||0)} km</div><div>—</div></div>`).join('')}</div><div class="rf-d2-total-strip"><div><span>Total distance</span><strong>${Math.round(s.distance).toLocaleString()} km</strong></div><div><span>Total spent</span><strong>${fmtEuro(s.spent)}</strong></div><div><span>Journal</span><strong>${s.entries} entries</strong></div></div></main>`;}
function dCosts(trip){const ex=expenses(trip.id);const agg=aggregate(ex);return`<main class="rf-d2-main">${hero(trip)}${tabs('costs')}<div class="rf-d2-ledger-hero"><div class="rf-d2-ledger-label">The trip ledger</div><div class="rf-d2-ledger-value">${fmtEuro(agg.total)}</div>${stamp(`${ex.length} entries`)}</div><div class="rf-d2-table">${ex.map((e)=>`<div class="rf-d2-table-row"><div>${esc(EXPENSE_CATEGORY_META[e.category]?.label||e.category)}</div><div>${esc(displayNameForUserId(e.user_id))}</div><div>${esc(fmtDate(e.date)||'')}</div><div>${fmtEuro(e.amount||0)}</div></div>`).join('')||'<div class="rf-d2-empty">No costs yet.</div>'}</div></main><aside class="rf-d2-aside"><div class="rf-d2-section-title">By category</div>${breaks(agg.cat)}<div class="rf-d2-section-title">By payer</div>${breaks(agg.payer)}</aside>`;}
function aggregate(ex){const cat=new Map(),payer=new Map();let total=0;ex.forEach((e)=>{const a=Number(e.amount)||0;total+=a;const c=EXPENSE_CATEGORY_META[e.category]?.label||e.category||'Other';cat.set(c,(cat.get(c)||0)+a);const p=displayNameForUserId(e.user_id);payer.set(p,(payer.get(p)||0)+a);});return{cat,payer,total};}
function breaks(map){return`<div class="rf-d2-breakdown">${[...map.entries()].map(([l,a])=>`<div class="rf-d2-break-row"><span>${esc(l)}</span><strong>${fmtEuro(a)}</strong></div>`).join('')||'No data.'}</div>`;}
function dItems(trip){const its=items(trip.id);const cs=cats(trip.id);const selected=STATE.selectedCategoryKey||slug(cs[0]?.name);const group=its.filter((it)=>slug(it.category?.name||'Other')===selected);return`<main class="rf-d2-main">${hero(trip)}${tabs('items')}<div class="rf-d2-items-hero"><div class="rf-d2-ledger-label">The packing list</div><div class="rf-d2-items-big">${its.filter((i)=>i.status==='packed').length} <span>of ${its.length} packed</span></div></div><div class="rf-d2-section-head"><div class="rf-d2-section-title">Categories</div></div><div class="rf-d2-item-cats">${cs.map((c,i)=>{const k=slug(c.name);const g=its.filter((it)=>slug(it.category?.name||'Other')===k);const p=g.filter((it)=>it.status==='packed').length;return`<button class="rf-d2-item-cat-row ${k===selected?'is-selected':''}" data-action="rf-d2-select-category" data-category="${k}" type="button"><span>${i+1}</span><strong>${esc(c.name)}</strong><span class="rf-d2-item-progress"><i style="width:${g.length?Math.round(p/g.length*100):0}%"></i></span><span>${p}/${g.length} packed</span><span>›</span></button>`;}).join('')}</div></main><aside class="rf-d2-aside"><div class="rf-d2-aside-head"><div class="rf-d2-aside-kicker">Category</div><h2 class="rf-d2-aside-title">${esc(cs.find((c)=>slug(c.name)===selected)?.name||'Items')}</h2></div>${filters(ITEM_FILTERS,STATE.itemStatusFilter||'all','rf-d2','item-filter')}<div class="rf-d2-item-list">${group.map(itemRow).join('')||'<div class="rf-d2-empty">No items here.</div>'}</div><form class="rf-d2-quick-form" data-action="rf-d2-item-form"><input class="rf-d2-input" name="text" placeholder="e.g. Rain gloves"><select class="rf-d2-input" name="category_id">${cs.map((c)=>`<option value="${esc(c.id||'')}">${esc(c.name)}</option>`).join('')}</select><button class="rf-d2-btn is-primary" type="submit">Add item</button></form></aside>`;}
function itemRow(it){return`<div class="rf-d2-item-row ${it.status==='packed'?'is-packed':''}"><button class="rf-d2-item-check" data-action="rf-d2-toggle-item" data-item-id="${esc(it.id)}" type="button">${it.status==='packed'?'✓':''}</button><div><strong>${esc(it.name)}</strong>${it.notes?`<small>${esc(it.notes)}</small>`:''}</div><span class="rf-d2-item-chip is-${esc(it.status||'planned')}"><span class="dot"></span>${esc(it.status||'planned')}</span>${avatar(displayNameForUserId(it.assigned_to||it.created_by))}</div>`;}
function dArchive(){const rows=archiveTrips();const l=lifetime();return`<main class="rf-d2-main is-archive"><div class="rf-d2-kicker">The collection</div><h1 class="rf-d2-hero-title">Archive</h1><div class="rf-d2-hero-sub">${rows.filter((t)=>t.status==='completed').length} put to bed · ${rows.filter((t)=>t.status==='cancelled').length} called off</div><div class="rf-d2-filter-row">${filters(ARCHIVE_FILTERS,STATE.archiveStatusFilter||'all')}${search(STATE.archiveFiltersOpen||!!STATE.archiveSearch,STATE.archiveSearch)}</div><div class="rf-d2-archive-totals"><h2>Lifetime totals</h2><div>Completed <strong>${l.completed}</strong></div><div>Distance <strong>${Math.round(l.distance).toLocaleString()}</strong></div><div>Spent <strong>${fmtEuro(l.spent)}</strong></div><div>Notes <strong>${l.entries}</strong></div></div><div class="rf-d2-section-head"><div class="rf-d2-section-title">The geography</div>${stamp('Heatmap')}</div><div class="rf-d2-map-card"><svg viewBox="0 0 700 320"><path class="rf-d2-map-land" d="M90 190 L140 120 L300 90 L450 125 L560 125 L610 170 L570 230 L420 245 L360 290 L250 270 L160 235 Z"></path><path class="rf-d2-map-route" d="M160 210 C240 160 315 210 390 180 S485 130 545 165"></path></svg></div>${rows.map((t)=>`<button class="rf-d2-archive-row" data-action="rf-d2-select-archived" data-trip-id="${esc(t.id)}" type="button"><span>${esc(tripNo(t))}</span><strong>${esc(t.title)}</strong><small>${esc(season(t))}</small><b>${fmtEuro(stats(t).spent)}</b></button>`).join('')}</main>`;}
function dAccount(){const l=lifetime();return`<main class="rf-d2-main is-account"><section class="rf-d2-account-card"><div class="rf-d2-account-avatar">${esc(userInitials(STATE.user))}</div><div><h1>${esc(userDisplayName(STATE.user))}</h1><p>${esc(STATE.user?.email||'')}</p><em>Routefolk member since 2023</em></div><button class="rf-d2-btn" data-action="rf-d2-manage-google">Manage Google account</button></section><section class="rf-d2-riders-card"><h2>Other riders</h2><p>${Math.max(0,STATE.profiles.length-1)} people you've ridden with</p></section><section class="rf-d2-mileage"><h2>Mileage to date</h2><div><strong>${l.trips}</strong><span>Trips</span></div><div><strong>${Math.round(l.distance).toLocaleString()}</strong><span>Distance</span></div><div><strong>${l.days}</strong><span>Days</span></div><div><strong>${fmtEuro(l.spent)}</strong><span>Spent</span></div></section><button class="rf-d2-btn" data-action="rf-d2-sign-out">Sign out</button><div class="rf-d2-version">routefolk · v0.6.2</div></main>`;}
function dCommand(){return`<div class="rf-d2-commandbar">${['Trips','Trip · Stages','Summary','Costs','Items','Archive','You'].map((x)=>`<span>${esc(x)}</span>`).join('')}</div>`;}

function mobile(){if(STATE.tab==='archive')return mArchive();if(STATE.tab==='account')return mAccount();const trip=currentTrip();if(!trip)return mTrips();if(STATE.view==='journal')return mJournal(trip);const v=tripView();if(v==='summary')return mSummary(trip);if(v==='costs')return mCosts(trip);if(v==='items')return mItems(trip);return mStages(trip);}
function mBar(active){return`<nav class="rf-m2-tab-bar"><div class="rf-m2-tab-row">${[['trips','Trips'],['archive','Archive'],['account','You']].map(([k,l])=>`<button class="rf-m2-tab-btn ${active===k?'is-active':''}" data-action="rf-m2-nav" data-tab="${k}" type="button"><span class="rf-m2-tab-bar-dash"></span><span class="rf-m2-tab-label">${l}</span></button>`).join('')}</div></nav>`;}
function mTrips(){return`<div class="rf-m2-screen"><header class="rf-m2-header"><div class="rf-m2-header-row"><div><div class="rf-m2-header-kicker">Routefolk</div><h1 class="rf-m2-header-title">Trips</h1><div class="rf-m2-header-sub">${activeTrips().length} on the road map · ${archiveTrips().length} in archive</div></div><button class="rf-m2-btn is-primary" data-action="rf-m2-new-trip">+ New</button></div></header><div class="rf-m2-body"><div class="rf-m2-filter-row">${filters(TRIP_FILTERS,STATE.tripStatusFilter||'all','rf-m2')}${search(STATE.tripFiltersOpen||!!STATE.tripSearch,STATE.tripSearch,'rf-m2')}</div>${activeTrips().map(mTripCard).join('')}</div>${mBar('trips')}</div>`;}
function mTripCard(t){const s=stats(t);return`<button class="rf-m2-trip-card" data-action="rf-m2-select-trip" data-trip-id="${esc(t.id)}"><div class="rf-m2-trip-no-ribbon">${esc(tripNo(t))}</div><div class="rf-m2-trip-card-title">${esc(t.title)}</div><div class="rf-m2-trip-card-sub">${esc(sub(t))}</div><div class="rf-m2-trip-card-meta"><div class="rf-m2-trip-card-dates">${esc(fmtDateRange(t.start_date,t.end_date))}</div>${statePill(t.status,'rf-m2')}</div><div class="rf-m2-trip-card-divider"><span class="rule"></span><span class="ornament">—</span><span class="rule"></span></div><div class="rf-m2-trip-card-foot"><div><div class="rf-m2-trip-card-num">${Math.round(s.distance).toLocaleString()}</div><div class="rf-m2-trip-card-unit">kilometres</div></div><div><div class="rf-m2-trip-card-num">${s.stages}</div><div class="rf-m2-trip-card-unit">stages</div></div></div></button>`;}
function mHead(t,sketch=true){return`<header class="rf-m2-detail-hero"><button class="rf-m2-back" data-action="rf-m2-back-to-trips">← Trips</button><div class="rf-m2-detail-kicker">${esc(tripNo(t))} · ${esc(season(t))}</div><h1 class="rf-m2-detail-title">${esc(t.title)}</h1><div class="rf-m2-detail-sub">${esc(sub(t))}</div><div class="rf-m2-detail-stamps">${statePill(t.status,'rf-m2')}${stamp('Group','accent','rf-m2')}</div>${sketch?route(t,'rf-m2'):''}</header>`;}
function mTabs(active){return`<nav class="rf-m2-tabs">${DETAIL_TABS.map((t)=>`<button class="rf-m2-tab ${active===t.key?'is-active':''}" data-action="rf-m2-tab" data-value="${t.key}">${t.label}</button>`).join('')}</nav>`;}
function mStages(t){return`<div class="rf-m2-screen">${mHead(t)}${mTabs('stages')}<div class="rf-m2-body">${stages(t.id).map((s,i)=>`<button class="rf-m2-stage" data-action="rf-m2-open-stage" data-stage-id="${esc(s.id)}"><div class="rf-m2-stage-no-col"><div class="rf-m2-stage-no">${i+1}</div><div class="rf-m2-stage-day">${esc(day(s.planned_date))}</div></div><div><div class="rf-m2-stage-title">${esc(s.start_location||'')} <span class="rf-m2-stage-to">to</span> ${esc(s.end_location||'')}</div><div class="rf-m2-stage-high">${esc(s.notes||'')}</div><div class="rf-m2-stage-mono">${Math.round(Number(s.distance_km)||0)} km · ${esc(fmtDate(s.planned_date)||'')}</div></div></button>`).join('')}<button class="rf-m2-btn is-dashed" data-action="rf-m2-add-stage">+ Add another stage</button></div>${mBar('trips')}</div>`;}
function mSummary(t){return`<div class="rf-m2-screen">${mHead(t,false)}${mTabs('summary')}<div class="rf-m2-body">${dSummary(t).replaceAll('rf-d2','rf-m2').replace(/<main[^>]*>|<\/main>/g,'')}</div>${mBar('trips')}</div>`;}
function mCosts(t){return`<div class="rf-m2-screen">${mHead(t,false)}${mTabs('costs')}<div class="rf-m2-body">${dCosts(t).split('</main>')[0].replaceAll('rf-d2','rf-m2').replace(/<main[^>]*>/,'')}</div>${mBar('trips')}</div>`;}
function mItems(t){return`<div class="rf-m2-screen">${mHead(t,false)}${mTabs('items')}<div class="rf-m2-body">${dItems(t).split('</main>')[0].replaceAll('rf-d2','rf-m2').replace(/<main[^>]*>/,'')}</div>${mBar('trips')}</div>`;}
function mJournal(t){const s=stages(t.id).find((x)=>x.id===STATE.selectedStageId)||stages(t.id)[0];return`<div class="rf-m2-screen"><div class="rf-m2-body"><button class="rf-m2-back" data-action="rf-m2-back-to-stages">← ${esc(t.title)}</button>${s?dAside(t,s).replaceAll('rf-d2','rf-m2').replace('<aside class="rf-m2-aside">','<div>').replace('</aside>','</div>'):''}</div>${mBar('trips')}</div>`;}
function mArchive(){return`<div class="rf-m2-screen"><header class="rf-m2-header"><div class="rf-m2-header-kicker">The collection</div><h1 class="rf-m2-header-title">Archive</h1></header><div class="rf-m2-body">${dArchive().replaceAll('rf-d2','rf-m2').replace(/<main[^>]*>|<\/main>/g,'')}</div>${mBar('archive')}</div>`;}
function mAccount(){return`<div class="rf-m2-screen"><header class="rf-m2-header"><div class="rf-m2-header-kicker">The bearer</div><h1 class="rf-m2-header-title">You</h1></header><div class="rf-m2-body">${dAccount().replaceAll('rf-d2','rf-m2').replace(/<main[^>]*>|<\/main>/g,'')}</div>${mBar('account')}</div>`;}

function render(){const app=$('app'),content=$('content');if(!app||!content)return;app.classList.add('is-v2');const html=STATE.user?`<div class="rf-v2-root-host">${window.matchMedia('(min-width:960px)').matches?desktop():mobile()}</div>`:`<div class="rf-v2-root-host">${window.matchMedia('(min-width:960px)').matches?'<div class="rf-d2-app"><main class="rf-d2-main"><button class="rf-d2-btn is-primary" data-action="rf-d2-sign-in">Sign in with Google</button></main></div>':'<div class="rf-m2-screen"><div class="rf-m2-body"><button class="rf-m2-btn is-primary is-block" data-action="rf-m2-sign-in">Sign in with Google</button></div></div>'}</div>`;if(html!==lastMarkup){content.innerHTML=html;lastMarkup=html;}}
async function saveStage(){const t=currentTrip();if(!t)return;await createStage(t.id,{start_location:$('v2-stage-from')?.value||'',end_location:$('v2-stage-to')?.value||'',planned_date:$('v2-stage-date')?.value||'',distance_km:$('v2-stage-km')?.value||'',notes:$('v2-stage-notes')?.value||''});STATE.wizard=null;}
async function saveJournal(){const s=stages(currentTrip()?.id).find((x)=>x.id===STATE.selectedStageId);if(!s)return;const date=s.planned_date||new Date().toISOString().slice(0,10);const time=$('v2-entry-time')?.value||'';await createEntry(s.id,{entry_type:'note',title:$('v2-entry-title')?.value||'',location:$('v2-entry-place')?.value||'',description:$('v2-entry-note')?.value||'',timestamp:time?`${date}T${time}:00`:null});STATE.wizard=null;}
function bind(){document.addEventListener('click',async(e)=>{const btn=e.target.closest?.('[data-action]');if(!btn)return;const a=btn.dataset.action;const tab=btn.dataset.tab;const val=btn.dataset.value;if(a.endsWith('nav')){STATE.tab=tab;STATE.view='list';STATE.viewTripId=null;STATE.wizard=null;}if(a.endsWith('select-trip')){STATE.tab='trips';STATE.view='detail';STATE.viewTripId=btn.dataset.tripId;STATE.wizard=null;}if(a.endsWith('back-to-trips')){STATE.view='list';STATE.viewTripId=null;STATE.wizard=null;}if(a.endsWith('tab')){STATE.view=viewForTab(val);STATE.wizard=null;}if(a.endsWith('select-stage')){STATE.selectedStageId=btn.dataset.stageId;STATE.wizard=null;}if(a.endsWith('open-stage')){STATE.selectedStageId=btn.dataset.stageId;STATE.view='journal';}if(a.endsWith('back-to-stages'))STATE.view='detail';if(a.endsWith('add-stage'))STATE.wizard='stage';if(a.endsWith('add-journal'))STATE.wizard='journal';if(a.endsWith('cancel-wizard'))STATE.wizard=null;if(a.endsWith('save-stage'))await saveStage();if(a.endsWith('save-journal'))await saveJournal();if(a.endsWith('search-toggle')){if(STATE.tab==='archive')STATE.archiveFiltersOpen=!STATE.archiveFiltersOpen;else STATE.tripFiltersOpen=!STATE.tripFiltersOpen;}if(a.endsWith('status-filter')){if(STATE.tab==='archive')STATE.archiveStatusFilter=val;else STATE.tripStatusFilter=val;}if(a.endsWith('select-category')||a.endsWith('open-category'))STATE.selectedCategoryKey=btn.dataset.category;if(a.endsWith('toggle-item'))await toggleTripItemPacked(items(currentTrip()?.id).find((it)=>it.id===btn.dataset.itemId));if(a.endsWith('sign-out'))document.getElementById('signOutBtn')?.click();if(a.endsWith('new-trip'))document.getElementById('newTripBtn')?.click();render();});document.addEventListener('input',(e)=>{const el=e.target;if(!el?.dataset?.action)return;if(el.dataset.action.endsWith('search-input')){if(STATE.tab==='archive')STATE.archiveSearch=el.value;else STATE.tripSearch=el.value;render();}});document.addEventListener('submit',async(e)=>{const form=e.target.closest?.('[data-action="rf-d2-item-form"]');if(!form)return;e.preventDefault();const trip=currentTrip();if(!trip)return;const fd=new FormData(form);await createTripItem(trip.id,{text:fd.get('text'),category_id:fd.get('category_id')||null,status:'planned'});form.reset();render();});window.addEventListener('resize',render);}
export function startRoutefolkV2(){if(started)return;started=true;bind();render();refreshTimer=setInterval(render,REFRESH_MS);}
startRoutefolkV2();
